### ISSUE TITLE
CPU Name is broken.

### ISSUE THREAD

**Issue by RealDexxo** [GabubuAvailable/gbfetch#1]
![image](https://user-images.githubusercontent.com/82178536/177306219-7515ee77-d0dc-4463-9703-642cf11e3d3a.png)

**Comment by GabubuAvailable** [comment]
Tell me the output of `lscpu | sed -nr '/Model name/ s/.*:\s*(.*) @ .*/\1/p'`

**Comment by GabubuAvailable** [comment]
You told me it doesn't work on Discord. Then might a problem from your linux distro. If you find the fix for your issue let me know :)
